/* Auto-generated by scripts/gen_gfx_shapes.py - do not edit. */
#include "gfx_shapes.h"

static const uint8_t shape00_cells[] = { 0x00, 0x00, 0x7f, 0x7f, 0x00, 0x7f, 0x7f, 0x7f, 0x7f, 0x7f, 0x7f, 0x7f, 0x00, 0x7f, 0x7f, 0x00, 0x7f, 0x7f, 0x7f, 0x00, 0x00, 0x00, 0x7f, 0x7f, 0x00 };

static const uint8_t shape01_cells[] = { 0x00, 0x7f, 0x7f, 0x00, 0x00, 0x7f, 0x7f, 0x7f, 0x7f, 0x00, 0x7f, 0x7f, 0x00, 0x7f, 0x7f, 0x00, 0x7f, 0x00, 0x7f, 0x7f, 0x00, 0x7f, 0x7f, 0x7f, 0x00 };

static const uint8_t shape02_cells[] = { 0x00, 0x7f, 0x7f, 0x00, 0x7f, 0x7f, 0x7f, 0x7f, 0x7f, 0x7f, 0x7f, 0x7f, 0x00, 0x7f, 0x7f, 0x00 };

static const uint8_t shape03_cells[] = { 0x00, 0x7f, 0x7f, 0x00, 0x7f, 0x7f, 0x7f, 0x7f, 0x7f, 0x7f, 0x7f, 0x7f, 0x7f, 0x7f, 0x7f, 0x7f };

static const uint8_t shape04_cells[] = { 0x00, 0x65, 0x3a, 0x00, 0x65, 0x3a, 0x65, 0x3a, 0x3a, 0x65, 0x3a, 0x65, 0x00, 0x3a, 0x65, 0x00 };

static const uint8_t shape05_cells[] = { 0x00, 0x7f, 0x00, 0x7f, 0x7f, 0x7f, 0x00, 0x7f, 0x00 };

static const uint8_t shape06_cells[] = { 0x00, 0x28, 0x00, 0x28, 0x00, 0x28, 0x00, 0x28, 0x00 };

static const uint8_t shape07_cells[] = { 0x00, 0x7f, 0x7f, 0x7f, 0x7f, 0x7f, 0x7f, 0x7f, 0x00 };

static const uint8_t shape08_cells[] = { 0x7f, 0x7f, 0x00, 0x7f, 0x7f, 0x7f, 0x00, 0x7f, 0x7f };

static const uint8_t shape09_cells[] = { 0x3a, 0x65, 0x65, 0x3a };

static const uint8_t shape10_cells[] = { 0x7f, 0x7f, 0x7f, 0x7f };

static const uint8_t shape11_cells[] = { 0x7f, 0x7f, 0x7f, 0x7f };

static const uint8_t shape12_cells[] = { 0x7f };

static const uint8_t shape13_cells[] = { 0x7f };

static const uint8_t shape14_cells[] = { 0x7f };

static const uint8_t shape15_cells[] = { 0x77 };

static const uint8_t shape16_cells[] = { 0x7b };

static const uint8_t shape17_cells[] = { 0x73 };

static const uint8_t shape18_cells[] = { 0x33 };

const GfxShapeDef gfx_shapes[] = {
    { 5, 5, shape00_cells },  /* shape01.dat: 5x5 teletext cells */
    { 5, 5, shape01_cells },  /* shape02.dat: 5x5 teletext cells */
    { 4, 4, shape02_cells },  /* shape03.dat: 4x4 teletext cells */
    { 4, 4, shape03_cells },  /* shape04.dat: 4x4 teletext cells */
    { 4, 4, shape04_cells },  /* shape05.dat: 4x4 teletext cells */
    { 3, 3, shape05_cells },  /* shape06.dat: 3x3 teletext cells */
    { 3, 3, shape06_cells },  /* shape07.dat: 3x3 teletext cells */
    { 3, 3, shape07_cells },  /* shape10.dat: 3x3 teletext cells */
    { 3, 3, shape08_cells },  /* shape11.dat: 3x3 teletext cells */
    { 2, 2, shape09_cells },  /* shape12.dat: 2x2 teletext cells */
    { 2, 2, shape10_cells },  /* shape14.dat: 2x2 teletext cells */
    { 2, 2, shape11_cells },  /* shape15.dat: 2x2 teletext cells */
    { 1, 1, shape12_cells },  /* shape18.dat: 1x1 teletext cells */
    { 1, 1, shape13_cells },  /* shape19.dat: 1x1 teletext cells */
    { 1, 1, shape14_cells },  /* shape20.dat: 1x1 teletext cells */
    { 1, 1, shape15_cells },  /* shape21.dat: 1x1 teletext cells */
    { 1, 1, shape16_cells },  /* shape22.dat: 1x1 teletext cells */
    { 1, 1, shape17_cells },  /* shape23.dat: 1x1 teletext cells */
    { 1, 1, shape18_cells },  /* shape24.dat: 1x1 teletext cells */
};

const uint8_t gfx_shape_count = sizeof(gfx_shapes) / sizeof(gfx_shapes[0]);

