#!/usr/bin/env python3
"""Generate BBC MODE 7 teletext graphics shape tables from bounce-world .dat files.

MODE 7 screen RAM uses mosaic codes in &20-&7F (not 160-255).  Codes &80-&FF
are alphabetic and display as text (e.g. '#' for 0xDF).  See iss-7c00.hex,
mkglob.bas, and https://edit.tf/

Sixel bit layout (same as teletext mosaics):
  bit0 bit1   top row
  bit2 bit3   middle row
  bit4 bit5   bottom row

Mosaic encoding (contiguous sixels in &20-&3F, then &60-&7F when bit5 set;
&40-&4F is unused):
  bit 5 clear -> &20 + pattern
  bit 5 set   -> &60 + (pattern & &1F)

Graphics colour controls in RAM are 17-23 (0x11 red .. 0x17 white).
ISS/mkglob uses 18 for green, 23 for white — not 145-151.
Empty playfield / transparent shape cells use 0 (leave &20 from clear).
"""

from __future__ import annotations

import sys
from pathlib import Path

TOP = 0b000011
MID = 0b001100
BOT = 0b110000
LFT = 0b010101
RGT = 0b101010
ALL = 0b111111

CHAR_SIXEL: dict[str, int] = {
    " ": 0,
    "m": ALL,
    "#": ALL,
    "a": LFT,
    "b": RGT,
    "c": BOT,
    "d": TOP,
    "e": 0b010001,
    "f": 0b100010,
    "g": 0b000001,
    "h": 0b000010,
    "i": 0b100011,
    "j": 0b010001,
    "k": 0b100010,
    "l": 0b010001,
    "r": TOP | LFT,
    ")": TOP | RGT,
    "L": BOT | LFT,
    "!": BOT | RGT,
    "t": LFT | MID,
    "J": RGT | MID,
    "T": TOP | MID,
    "2": BOT | MID,
    "-": MID,
    "|": ALL,
    "+": ALL,
    "*": MID | TOP | BOT,
    ".": 0b001000,
    "O": TOP | BOT | LFT | RGT,
    "X": 0b010010 | 0b100001 | 0b000100,
    "@": TOP | BOT | 0b001010,
    "V": 0b100010 | 0b010001 | BOT,
    "^": TOP | 0b010010,
    "W": LFT | RGT | MID | 0b000010,
    "M": LFT | RGT | TOP | MID,
    "/": 0b000010 | 0b001000 | 0b010000,
    "\\": 0b000001 | 0b000100 | 0b100000,
}

SHAPE_FILES = [
    "shape01.dat",
    "shape02.dat",
    "shape03.dat",
    "shape04.dat",
    "shape05.dat",
    "shape06.dat",
    "shape07.dat",
    "shape10.dat",
    "shape11.dat",
    "shape12.dat",
    "shape14.dat",
    "shape15.dat",
    "shape18.dat",
    "shape19.dat",
    "shape20.dat",
    "shape21.dat",
    "shape22.dat",
    "shape23.dat",
    "shape24.dat",
]


def load_shape(path: Path) -> list[str]:
    lines = path.read_text(encoding="utf-8").splitlines()
    rows = [line.rstrip("\n") for line in lines[1:] if line.strip()]
    width = len(rows[0])
    for row in rows:
        if len(row) != width:
            raise ValueError(f"{path}: ragged rows")
    return rows


def char_to_sixel(ch: str) -> int:
    if ch in CHAR_SIXEL:
        return CHAR_SIXEL[ch]
    o = ord(ch)
    if 32 <= o < 127:
        return ALL if ch not in " ." else 0
    return ALL


def mode7_gfx_char(pattern: int) -> int:
    """Map a 6-bit sixel pattern to a MODE 7 mosaic screen byte."""
    pattern &= 0x3F
    if pattern & 0x20:
        return 0x60 + (pattern & 0x1F)
    return 0x20 + pattern


def shape_to_cells(rows: list[str]) -> tuple[int, int, bytes]:
    char_h = len(rows)
    char_w = len(rows[0])
    cells = bytearray(char_w * char_h)
    idx = 0
    for row in rows:
        for ch in row:
            pat = char_to_sixel(ch)
            cells[idx] = mode7_gfx_char(pat) if pat else 0
            idx += 1
    return char_w, char_h, bytes(cells)


def fmt_bytes(data: bytes) -> str:
    return ", ".join(f"0x{b:02x}" for b in data)


def main() -> int:
    if len(sys.argv) != 3:
        print(f"usage: {sys.argv[0]} <shapes-dir> <output.c>", file=sys.stderr)
        return 1

    shapes_dir = Path(sys.argv[1])
    out_path = Path(sys.argv[2])

    parts: list[str] = [
        "/* Auto-generated by scripts/gen_gfx_shapes.py - do not edit. */",
        '#include "gfx_shapes.h"',
        "",
    ]

    table_rows: list[str] = []
    comments: list[str] = []

    for idx, name in enumerate(SHAPE_FILES):
        path = shapes_dir / name
        rows = load_shape(path)
        width, height, data = shape_to_cells(rows)
        sym = f"shape{idx:02d}_cells"
        parts.append(f"static const uint8_t {sym}[] = {{ {fmt_bytes(data)} }};")
        parts.append("")
        table_rows.append(f"    {{ {width}, {height}, {sym} }},")
        comments.append(f"/* {name}: {height}x{width} teletext cells */")

    parts.append("const GfxShapeDef gfx_shapes[] = {")
    parts.extend(f"{row}  {comment}" for row, comment in zip(table_rows, comments))
    parts.append("};")
    parts.append("")
    parts.append("const uint8_t gfx_shape_count = sizeof(gfx_shapes) / sizeof(gfx_shapes[0]);")
    parts.append("")

    out_path.write_text("\n".join(parts) + "\n", encoding="utf-8")
    print(f"Wrote {out_path} ({len(SHAPE_FILES)} shapes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
