#!/usr/bin/env python3
"""Generate embedded client shape tables from bounce-world .dat files.

Output matches the x-shape-data TCP payload (per-shape: id, width, coded bytes)
using the same neutral character mapping as ShapeCreator.kt on the server.
Platforms call convert_chars() at load time for local display codes.
"""

from __future__ import annotations

import sys
from pathlib import Path

SHAPE_FILES = [
    "shape01.dat",
    "shape02.dat",
    "shape03.dat",
    "shape04.dat",
    "shape05.dat",
    "shape06.dat",
    "shape07.dat",
    "shape10.dat",
    "shape11.dat",
    "shape12.dat",
    "shape14.dat",
    "shape15.dat",
    "shape18.dat",
    "shape19.dat",
    "shape20.dat",
    "shape21.dat",
    "shape22.dat",
    "shape23.dat",
    "shape24.dat",
]

UNICODE_MAP = {
    "┌": "r",
    "┐": ")",
    "└": "L",
    "┘": "!",
    "┤": "J",
    "├": "t",
    "┬": "T",
    "┴": "2",
    "│": "|",
    "─": "-",
    "┼": "+",
    "▌": "a",
    "▐": "b",
    "▄": "c",
    "▀": "d",
    "▖": "e",
    "▗": "f",
    "▘": "g",
    "▝": "h",
    "▜": "i",
    "▛": "j",
    "▟": "k",
    "▙": "l",
    "█": "m",
    "▚": "n",
    "▞": "p",
}


def neutralize(text: str) -> bytes:
    out = bytearray()
    for ch in text.replace("\r", "").replace("\n", ""):
        if ch in UNICODE_MAP:
            out.append(ord(UNICODE_MAP[ch]))
        else:
            out.append(ord(ch))
    return bytes(out)


def load_shape(path: Path) -> tuple[int, bytes]:
    lines = path.read_text(encoding="utf-8").splitlines()
    if not lines:
        raise ValueError(f"{path}: empty file")
    _mass = float(lines[0])
    payload = neutralize("".join(lines[1:]))
    side = int(len(payload) ** 0.5)
    if side * side != len(payload):
        raise ValueError(f"{path}: not square ({len(payload)} cells)")
    return side, payload


def fmt_bytes(data: bytes) -> str:
    return ", ".join(f"0x{b:02x}" for b in data)


def main() -> int:
    if len(sys.argv) != 4:
        print(
            f"usage: {sys.argv[0]} <shapes-dir> <output.c> <output.h>",
            file=sys.stderr,
        )
        return 1

    shapes_dir = Path(sys.argv[1])
    out_c = Path(sys.argv[2])
    out_h = Path(sys.argv[3])

    parts: list[str] = [
        "/* Auto-generated by scripts/gen_embedded_shapes.py - do not edit. */",
        '#include "embedded_shapes.h"',
        "",
        f"const uint8_t embedded_shape_count = {len(SHAPE_FILES)};",
        "",
        "/* Wire format: id, width, width*width neutral coded bytes per shape. */",
        "static const uint8_t embedded_shape_blob[] = {",
    ]
    total_cells = 0

    for shape_id, name in enumerate(SHAPE_FILES):
        path = shapes_dir / name
        width, payload = load_shape(path)
        total_cells += len(payload)
        parts.append(f"    /* {name}: id={shape_id} {width}x{width} */")
        blob = [str(shape_id), str(width), * [f"0x{b:02x}" for b in payload]]
        parts.append("    " + ", ".join(blob) + ",")

    parts.extend(
        [
            "};",
            "",
            "const uint8_t *const embedded_shape_data = embedded_shape_blob;",
            "const uint16_t embedded_shape_data_len = sizeof(embedded_shape_blob);",
            "",
        ]
    )

    out_c.write_text("\n".join(parts), encoding="utf-8")

    out_h.write_text(
        "\n".join(
            [
                "#ifndef BWC_EMBEDDED_SHAPES_H",
                "#define BWC_EMBEDDED_SHAPES_H",
                "",
                "#include <stdint.h>",
                "",
                "extern const uint8_t embedded_shape_count;",
                "extern const uint8_t *const embedded_shape_data;",
                "extern const uint16_t embedded_shape_data_len;",
                "",
                "#endif /* BWC_EMBEDDED_SHAPES_H */",
                "",
            ]
        ),
        encoding="utf-8",
    )

    print(
        f"Wrote {out_c} and {out_h} "
        f"({len(SHAPE_FILES)} shapes, {total_cells} cells)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
